name: Nuxt 3 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt 3 app
        run: npm run build

      - name: Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: nuxt-output
          path: .output
